name: Lotus News Dashboard CI/CD Pipeline

# 1. TRIGGER WORKFLOW
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  # Allow manual run via Github interface
  workflow_dispatch:

jobs:
  # ====================================================================
  # JOB 1: CI Pipeline (Code Quality, Analysis, and Testing)
  # Run on Linux platform (Ubuntu) cause more fast and saving time than macOS
  # ====================================================================
  ci_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java (for Android build tools)
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Cache Flutter dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.FLUTTER_ROOT }}/.pub-cache
          key: ${{ runner.os }}-pub-cache-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-cache-

      - name: Get Dependencies
        run: flutter pub get

      - name: Analyze Code (Static Analysis)
        run: flutter analyze

      - name: Check Formatting
        run: dart format --set-exit-if-changed .

      - name: Run Tests
        run: flutter test
